
version: '3.9'
services:

  api:
    container_name: api
    restart: always
    env_file: .env
    build: .
    volumes:
      - .:/code
    networks:
      - web_network
    depends_on:
      - redis

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - api

  redis:
    image: "redis:alpine"
    networks:
      - web_network
  
  celery:
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A NotificationApi worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
    networks:
      - web_network
    depends_on:
      - api
      - redis

  celery-beat:
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A NotificationApi beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
    networks:
      - web_network
    depends_on:
      - api
      - redis

  celery-flower:
    build: .
    restart: always
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A NotificationApi flower --loglevel=DEBUG --port=8888
    ports:
      - 8888:8888
    networks:
      - web_network
    depends_on:
      - api
      - redis

networks:
  web_network:
    driver: bridge
