
version: '3.9'
services:

  api:
    restart: always
    container_name: api
    env_file: NotificationApi/.env
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/NotificationApi/staticfiles
      - .:/home/app/NotificationApi
    networks:
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/NotificationApi/staticfiles
    networks:
      - web_network
    depends_on:
      - api

networks:
  web_network:
    driver: bridge

volumes:
  static_volume:
