version: '3.9' 
services:
  api:
    image: api
    container_name: api
    restart: always
    env_file: .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 5678:5678
      - 5005:5005
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

