---
  name: 'deploy'
  
  # yamllint disable-line rule:truthy
  on:
    workflow_dispatch:
    push:
      branches:
        - master
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Set up qemu
          uses: docker/setup-qemu-action@v3
  
        - name: Set up docker buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - id: lower-repo
          shell: pwsh
          run: |
            "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.sha }}
  
        - name: Push to dokku
          uses: dokku/github-action@master
          with:
            git_remote_url: 'ssh://dokku@dokku.me:22/dev-notifications'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            deploy_docker_image: ${{ github.repository }}:${{ github.sha }}
